const PLAY_OPERATION = "PLAY";
const CONNECTION_OPERATION = "CONNECTION";
const INPUT_OPERATION = "INPUT";

const SERVER_SENDER = "server";
const RPI_SENDER = "rpi";

const RPI_CONNECTED_STATUS = "connected";
const RPI_PLAYING_STATUS = "playing";

export {PLAY_OPERATION, CONNECTION_OPERATION, INPUT_OPERATION, SERVER_SENDER, RPI_SENDER, RPI_CONNECTED_STATUS, RPI_PLAYING_STATUS}